const paths = {
  express_dev: {
    "process_env": {
      "ALLUSERSPROFILE": "C:/ProgramData",
      "AMDRMPATH": "C:/Program Files/AMD/RyzenMaster/",
      "APPDATA": "C:/Users/elias/AppData/Roaming",
      "ChocolateyInstall": "C:/ProgramData/chocolatey",
      "ChocolateyLastPathUpdate": "133077435083688729",
      "CHROME_CRASHPAD_PIPE_NAME": "//./pipe/crashpad_6880_APIFCAWAGFDRVGXX",
      "COLOR": "1",
      "COLORTERM": "truecolor",
      "CommonProgramFiles": "C:/Program Files/Common Files",
      "CommonProgramFiles(x86)": "C:/Program Files (x86)/Common Files",
      "CommonProgramW6432": "C:/Program Files/Common Files",
      "COMPUTERNAME": "DESKTOP-N4H17RS",
      "ComSpec": "C:/Windows/system32/cmd.exe",
      "DriverData": "C:/Windows/System32/Drivers/DriverData",
      "EDITOR": "C:/Windows/notepad.exe",
      "FPS_BROWSER_APP_PROFILE_STRING": "Internet Explorer",
      "FPS_BROWSER_USER_PROFILE_STRING": "Default",
      "GIT_ASKPASS": "c:/Users/elias/AppData/Local/Programs/Microsoft VS Code/resources/app/extensions/git/dist/askpass.sh",
      "HOME": "C:/Users/elias",
      "HOMEDRIVE": "C:",
      "HOMEPATH": "/Users/elias",
      "INIT_CWD": "C:/Users/elias/Desktop/Javascript/Precision/electron_web_template/server",
      "LANG": "en_US.UTF-8",
      "LOCALAPPDATA": "C:/Users/elias/AppData/Local",
      "LOGONSERVER": "//DESKTOP-N4H17RS",
      "NODE": "C:/Program Files/nodejs/node.exe",
      "NODE_EXE": "C:/Program Files/nodejs//node.exe",
      "NPM_CLI_JS": "C:/Users/elias/AppData/Roaming/npm/node_modules/npm/bin/npm-cli.js",
      "npm_command": "run-script",
      "npm_config_cache": "C:/Users/elias/AppData/Local/npm-cache",
      "npm_config_globalconfig": "C:/Users/elias/AppData/Roaming/npm/etc/npmrc",
      "npm_config_global_prefix": "C:/Users/elias/AppData/Roaming/npm",
      "npm_config_init_module": "C:/Users/elias/.npm-init.js",
      "npm_config_local_prefix": "C:/Users/elias/Desktop/Javascript/Precision/electron_web_template/server",
      "npm_config_metrics_registry": "https://registry.npmjs.org/",
      "npm_config_node_gyp": "C:/Users/elias/AppData/Roaming/npm/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js",
      "npm_config_noproxy": "",
      "npm_config_prefix": "C:/Users/elias/AppData/Roaming/npm",
      "npm_config_userconfig": "C:/Users/elias/.npmrc",
      "npm_config_user_agent": "npm/9.5.0 node/v18.16.0 win32 x64 workspaces/false",
      "npm_execpath": "C:/Users/elias/AppData/Roaming/npm/node_modules/npm/bin/npm-cli.js",
      "npm_lifecycle_event": "dev",
      "npm_lifecycle_script": "nodemon src/server.js",
      "npm_node_execpath": "C:/Program Files/nodejs/node.exe",
      "npm_package_json": "C:/Users/elias/Desktop/Javascript/Precision/electron_web_template/server/package.json",
      "npm_package_name": "server",
      "npm_package_version": "1.0.0",
      "NPM_PREFIX_NPM_CLI_JS": "C:/Users/elias/AppData/Roaming/npm/node_modules/npm/bin/npm-cli.js",
      "NUMBER_OF_PROCESSORS": "16",
      "OneDrive": "C:/Users/elias/OneDrive",
      "OneDriveConsumer": "C:/Users/elias/OneDrive",
      "ORIGINAL_XDG_CURRENT_DESKTOP": "undefined",
      "OS": "Windows_NT",
      "Path": "C:/Users/elias/Desktop/Javascript/Precision/electron_web_template/server/node_modules/.bin;C:/Users/elias/Desktop/Javascript/Precision/electron_web_template/node_modules/.bin;C:/Users/elias/Desktop/Javascript/Precision/node_modules/.bin;C:/Users/elias/Desktop/Javascript/node_modules/.bin;C:/Users/elias/Desktop/node_modules/.bin;C:/Users/elias/node_modules/.bin;C:/Users/node_modules/.bin;C:/node_modules/.bin;C:/Users/elias/AppData/Roaming/npm/node_modules/npm/node_modules/@npmcli/run-script/lib/node-gyp-bin;C:/Program Files/Eclipse Foundation/jdk-11.0.12.7-hotspot/bin;C:/Windows/system32;C:/Windows;C:/Windows/System32/Wbem;C:/Windows/System32/WindowsPowerShell/v1.0/;C:/Windows/System32/OpenSSH/;C:/Program Files (x86)/NVIDIA Corporation/PhysX/Common;C:/Program Files/Microsoft SQL Server/130/Tools/Binn/;C:/Program Files/dotnet/;C:/Program Files/Microsoft SQL Server/Client SDK/ODBC/170/Tools/Binn/;C:/Program Files/Git/cmd;C:/ProgramData/chocolatey/bin;;C:/Program Files/NVIDIA Corporation/NVIDIA NvDLISR;C:/Program Files/nodejs/;C:/Users/elias/AppData/Local/Programs/Python/Python310/Scripts/;C:/Users/elias/AppData/Local/Programs/Python/Python310/;C:/Users/elias/AppData/Local/Microsoft/WindowsApps;;C:/Users/elias/AppData/Local/Programs/Microsoft VS Code/bin;C:/Users/elias/.dotnet/tools;C:/Program Files (x86)/Nmap;C:/Users/elias/AppData/Roaming/npm",
      "PATHEXT": ".COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.CPL",
      "PROCESSOR_ARCHITECTURE": "AMD64",
      "PROCESSOR_IDENTIFIER": "AMD64 Family 25 Model 33 Stepping 2, AuthenticAMD",
      "PROCESSOR_LEVEL": "25",
      "PROCESSOR_REVISION": "2102",
      "ProgramData": "C:/ProgramData",
      "ProgramFiles": "C:/Program Files",
      "ProgramFiles(x86)": "C:/Program Files (x86)",
      "ProgramW6432": "C:/Program Files",
      "PROMPT": "$P$G",
      "PSModulePath": "C:/Users/elias/Documents/WindowsPowerShell/Modules;C:/Program Files/WindowsPowerShell/Modules;C:/Windows/system32/WindowsPowerShell/v1.0/Modules",
      "PUBLIC": "C:/Users/Public",
      "SESSIONNAME": "Console",
      "SystemDrive": "C:",
      "SystemRoot": "C:/Windows",
      "TEMP": "C:/Users/elias/AppData/Local/Temp",
      "TERM_PROGRAM": "vscode",
      "TERM_PROGRAM_VERSION": "1.82.0",
      "TMP": "C:/Users/elias/AppData/Local/Temp",
      "USERDOMAIN": "DESKTOP-N4H17RS",
      "USERDOMAIN_ROAMINGPROFILE": "DESKTOP-N4H17RS",
      "USERNAME": "elias",
      "USERPROFILE": "C:/Users/elias",
      "VSCODE_GIT_ASKPASS_EXTRA_ARGS": "--ms-enable-electron-run-as-node",
      "VSCODE_GIT_ASKPASS_MAIN": "c:/Users/elias/AppData/Local/Programs/Microsoft VS Code/resources/app/extensions/git/dist/askpass-main.js",
      "VSCODE_GIT_ASKPASS_NODE": "C:/Users/elias/AppData/Local/Programs/Microsoft VS Code/Code.exe",
      "VSCODE_GIT_IPC_HANDLE": "//./pipe/vscode-git-5307555524-sock",
      "windir": "C:/Windows"
    },
    "process_cwd": "C:/Users/elias/Desktop/Javascript/Precision/electron_web_template/server",
    "process_execPath": "C:/Program Files/nodejs/node.exe",
    "path_resolve": "C:/Users/elias/Desktop/Javascript/Precision/electron_web_template/server"
  },
  express_packed: {
    "process_env": {
      "ALLUSERSPROFILE": "C:/ProgramData",
      "AMDRMPATH": "C:/Program Files/AMD/RyzenMaster/",
      "APPDATA": "C:/Users/elias/AppData/Roaming",
      "ChocolateyInstall": "C:/ProgramData/chocolatey",
      "ChocolateyLastPathUpdate": "133077435083688729",
      "CommonProgramFiles": "C:/Program Files/Common Files",
      "CommonProgramFiles(x86)": "C:/Program Files (x86)/Common Files",
      "CommonProgramW6432": "C:/Program Files/Common Files",
      "COMPUTERNAME": "DESKTOP-N4H17RS",
      "ComSpec": "C:/Windows/system32/cmd.exe",
      "DriverData": "C:/Windows/System32/Drivers/DriverData",
      "FPS_BROWSER_APP_PROFILE_STRING": "Internet Explorer",
      "FPS_BROWSER_USER_PROFILE_STRING": "Default",
      "HOMEDRIVE": "C:",
      "HOMEPATH": "/Users/elias",
      "LOCALAPPDATA": "C:/Users/elias/AppData/Local",
      "LOGONSERVER": "//DESKTOP-N4H17RS",
      "NUMBER_OF_PROCESSORS": "16",
      "OneDrive": "C:/Users/elias/OneDrive",
      "OneDriveConsumer": "C:/Users/elias/OneDrive",
      "OS": "Windows_NT",
      "Path": "C:/Program Files/Eclipse Foundation/jdk-11.0.12.7-hotspot/bin;C:/Windows/system32;C:/Windows;C:/Windows/System32/Wbem;C:/Windows/System32/WindowsPowerShell/v1.0/;C:/Windows/System32/OpenSSH/;C:/Program Files (x86)/NVIDIA Corporation/PhysX/Common;C:/Program Files/Microsoft SQL Server/130/Tools/Binn/;C:/Program Files/dotnet/;C:/Program Files/Microsoft SQL Server/Client SDK/ODBC/170/Tools/Binn/;C:/Program Files/Git/cmd;C:/ProgramData/chocolatey/bin;;C:/Program Files/NVIDIA Corporation/NVIDIA NvDLISR;C:/Program Files/nodejs/;C:/Users/elias/AppData/Local/Programs/Python/Python310/Scripts/;C:/Users/elias/AppData/Local/Programs/Python/Python310/;C:/Users/elias/AppData/Local/Microsoft/WindowsApps;;C:/Users/elias/AppData/Local/Programs/Microsoft VS Code/bin;C:/Users/elias/.dotnet/tools;C:/Program Files (x86)/Nmap;C:/Users/elias/AppData/Roaming/npm",
      "PATHEXT": ".COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC",
      "PROCESSOR_ARCHITECTURE": "AMD64",
      "PROCESSOR_IDENTIFIER": "AMD64 Family 25 Model 33 Stepping 2, AuthenticAMD",
      "PROCESSOR_LEVEL": "25",
      "PROCESSOR_REVISION": "2102",
      "ProgramData": "C:/ProgramData",
      "ProgramFiles": "C:/Program Files",
      "ProgramFiles(x86)": "C:/Program Files (x86)",
      "ProgramW6432": "C:/Program Files",
      "PSModulePath": "C:/Program Files/WindowsPowerShell/Modules;C:/Windows/system32/WindowsPowerShell/v1.0/Modules",
      "PUBLIC": "C:/Users/Public",
      "SESSIONNAME": "Console",
      "SystemDrive": "C:",
      "SystemRoot": "C:/Windows",
      "TEMP": "C:/Users/elias/AppData/Local/Temp",
      "TMP": "C:/Users/elias/AppData/Local/Temp",
      "USERDOMAIN": "DESKTOP-N4H17RS",
      "USERDOMAIN_ROAMINGPROFILE": "DESKTOP-N4H17RS",
      "USERNAME": "elias",
      "USERPROFILE": "C:/Users/elias",
      "windir": "C:/Windows",
      "__COMPAT_LAYER": "DetectorsAppHealth"
    },
    "process_cwd": "C:/Users/elias/Desktop/Javascript/Precision/electron_web_template/server/pack",
    "process_execPath": "C:/Users/elias/Desktop/Javascript/Precision/electron_web_template/server/pack/executable.exe",
    "path_resolve": "C:/Users/elias/Desktop/Javascript/Precision/electron_web_template/server/pack"
  },
  electron_dev: {
    "process_env": {
      "HOMEDRIVE": "C:",
      "HOMEPATH": "/Users/elias",
      "LOGONSERVER": "//DESKTOP-N4H17RS",
      "NODE_ENV_ELECTRON": "development",
      "PATH": "C:/Users/elias/Desktop/Javascript/Precision/electron_web_template/node_modules/.bin;C:/Users/elias/Desktop/Javascript/Precision/node_modules/.bin;C:/Users/elias/Desktop/Javascript/node_modules/.bin;C:/Users/elias/Desktop/node_modules/.bin;C:/Users/elias/node_modules/.bin;C:/Users/node_modules/.bin;C:/node_modules/.bin;C:/Users/elias/AppData/Roaming/npm/node_modules/npm/node_modules/@npmcli/run-script/lib/node-gyp-bin;C:/Program Files/Eclipse Foundation/jdk-11.0.12.7-hotspot/bin;C:/Windows/system32;C:/Windows;C:/Windows/System32/Wbem;C:/Windows/System32/WindowsPowerShell/v1.0/;C:/Windows/System32/OpenSSH/;C:/Program Files (x86)/NVIDIA Corporation/PhysX/Common;C:/Program Files/Microsoft SQL Server/130/Tools/Binn/;C:/Program Files/dotnet/;C:/Program Files/Microsoft SQL Server/Client SDK/ODBC/170/Tools/Binn/;C:/Program Files/Git/cmd;C:/ProgramData/chocolatey/bin;;C:/Program Files/NVIDIA Corporation/NVIDIA NvDLISR;C:/Program Files/nodejs/;C:/Users/elias/AppData/Local/Programs/Python/Python310/Scripts/;C:/Users/elias/AppData/Local/Programs/Python/Python310/;C:/Users/elias/AppData/Local/Microsoft/WindowsApps;;C:/Users/elias/AppData/Local/Programs/Microsoft VS Code/bin;C:/Users/elias/.dotnet/tools;C:/Program Files (x86)/Nmap;C:/Users/elias/AppData/Roaming/npm",
      "SYSTEMDRIVE": "C:",
      "SYSTEMROOT": "C:/Windows",
      "TEMP": "C:/Users/elias/AppData/Local/Temp",
      "USERDOMAIN": "DESKTOP-N4H17RS",
      "USERNAME": "elias",
      "USERPROFILE": "C:/Users/elias",
      "WINDIR": "C:/Windows"
    },
    "process_cwd": "C:/Users/elias/Desktop/Javascript/Precision/electron_web_template",
    "process_execPath": "C:/Program Files/nodejs/node.exe",
    "path_resolve": "C:/Users/elias/Desktop/Javascript/Precision/electron_web_template"
  },
  electron_prod: {
    "process_env": {
      "HOMEDRIVE": "C:",
      "HOMEPATH": "/Users/elias",
      "LOGONSERVER": "//DESKTOP-N4H17RS",
      "NODE_ENV_ELECTRON": "development",
      "PATH": "C:/Users/elias/Desktop/Javascript/Precision/electron_web_template/node_modules/.bin;C:/Users/elias/Desktop/Javascript/Precision/node_modules/.bin;C:/Users/elias/Desktop/Javascript/node_modules/.bin;C:/Users/elias/Desktop/node_modules/.bin;C:/Users/elias/node_modules/.bin;C:/Users/node_modules/.bin;C:/node_modules/.bin;C:/Users/elias/AppData/Roaming/npm/node_modules/npm/node_modules/@npmcli/run-script/lib/node-gyp-bin;C:/Program Files/Eclipse Foundation/jdk-11.0.12.7-hotspot/bin;C:/Windows/system32;C:/Windows;C:/Windows/System32/Wbem;C:/Windows/System32/WindowsPowerShell/v1.0/;C:/Windows/System32/OpenSSH/;C:/Program Files (x86)/NVIDIA Corporation/PhysX/Common;C:/Program Files/Microsoft SQL Server/130/Tools/Binn/;C:/Program Files/dotnet/;C:/Program Files/Microsoft SQL Server/Client SDK/ODBC/170/Tools/Binn/;C:/Program Files/Git/cmd;C:/ProgramData/chocolatey/bin;;C:/Program Files/NVIDIA Corporation/NVIDIA NvDLISR;C:/Program Files/nodejs/;C:/Users/elias/AppData/Local/Programs/Python/Python310/Scripts/;C:/Users/elias/AppData/Local/Programs/Python/Python310/;C:/Users/elias/AppData/Local/Microsoft/WindowsApps;;C:/Users/elias/AppData/Local/Programs/Microsoft VS Code/bin;C:/Users/elias/.dotnet/tools;C:/Program Files (x86)/Nmap;C:/Users/elias/AppData/Roaming/npm",
      "SYSTEMDRIVE": "C:",
      "SYSTEMROOT": "C:/Windows",
      "TEMP": "C:/Users/elias/AppData/Local/Temp",
      "USERDOMAIN": "DESKTOP-N4H17RS",
      "USERNAME": "elias",
      "USERPROFILE": "C:/Users/elias",
      "WINDIR": "C:/Windows"
    },
    "process_cwd": "C:/Users/elias/Desktop/Javascript/Precision/electron_web_template",
    "process_execPath": "C:/Users/elias/Desktop/Javascript/Precision/electron_web_template/server/pack/executable.exe",
    "path_resolve": "C:/Users/elias/Desktop/Javascript/Precision/electron_web_template"
  }
}